"""baseline: 全量表结构（watchlist/paper/review/predict/minute_decisions）

Revision ID: 91f8ea3c3a3e
Revises: 
Create Date: 2026-08-30 13:38:42.216026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f8ea3c3a3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minute_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.String(length=48), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('trigger_ts', sa.String(length=32), nullable=False),
    sa.Column('signal_price', sa.Float(), nullable=False),
    sa.Column('bias', sa.String(length=8), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('triggered', sa.Text(), nullable=False),
    sa.Column('invalidate_condition', sa.Text(), nullable=False),
    sa.Column('executed', sa.Integer(), nullable=False),
    sa.Column('executed_price', sa.Float(), nullable=True),
    sa.Column('realized_spread_pct', sa.Float(), nullable=True),
    sa.Column('best_price', sa.Float(), nullable=True),
    sa.Column('worst_price', sa.Float(), nullable=True),
    sa.Column('optimal_spread_pct', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=12), nullable=True),
    sa.Column('error_attribution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minute_decisions_created_at'), 'minute_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_minute_decisions_decision_id'), 'minute_decisions', ['decision_id'], unique=True)
    op.create_index(op.f('ix_minute_decisions_outcome'), 'minute_decisions', ['outcome'], unique=False)
    op.create_index(op.f('ix_minute_decisions_symbol'), 'minute_decisions', ['symbol'], unique=False)
    op.create_index(op.f('ix_minute_decisions_trade_date'), 'minute_decisions', ['trade_date'], unique=False)
    op.create_index(op.f('ix_minute_decisions_trigger_ts'), 'minute_decisions', ['trigger_ts'], unique=False)
    op.create_table('paper_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('initial_cash', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_order_status'), 'paper_order', ['status'], unique=False)
    op.create_index(op.f('ix_paper_order_symbol'), 'paper_order', ['symbol'], unique=False)
    op.create_table('paper_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('frozen_today', sa.Integer(), nullable=False),
    sa.Column('buy_date', sa.String(length=8), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_position_symbol'), 'paper_position', ['symbol'], unique=True)
    op.create_table('prediction_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.String(length=40), nullable=False),
    sa.Column('target_date', sa.String(length=8), nullable=False),
    sa.Column('context', sa.String(length=16), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('theme_count', sa.Integer(), nullable=False),
    sa.Column('verdict_summary', sa.String(length=200), nullable=False),
    sa.Column('verify_status', sa.String(length=12), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('report_path', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_reports_context'), 'prediction_reports', ['context'], unique=False)
    op.create_index(op.f('ix_prediction_reports_created_at'), 'prediction_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_prediction_reports_prediction_id'), 'prediction_reports', ['prediction_id'], unique=True)
    op.create_index(op.f('ix_prediction_reports_target_date'), 'prediction_reports', ['target_date'], unique=False)
    op.create_index(op.f('ix_prediction_reports_verify_status'), 'prediction_reports', ['verify_status'], unique=False)
    op.create_table('prediction_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.String(length=40), nullable=False),
    sa.Column('target_date', sa.String(length=8), nullable=False),
    sa.Column('theme', sa.String(length=60), nullable=False),
    sa.Column('verdict', sa.String(length=12), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('verify_outcome', sa.String(length=12), nullable=True),
    sa.Column('formed', sa.Integer(), nullable=True),
    sa.Column('limit_up_count_d1', sa.Integer(), nullable=True),
    sa.Column('leader_actual', sa.String(length=60), nullable=True),
    sa.Column('leader_hit', sa.Integer(), nullable=True),
    sa.Column('verify_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_themes_created_at'), 'prediction_themes', ['created_at'], unique=False)
    op.create_index(op.f('ix_prediction_themes_prediction_id'), 'prediction_themes', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_prediction_themes_target_date'), 'prediction_themes', ['target_date'], unique=False)
    op.create_index(op.f('ix_prediction_themes_theme'), 'prediction_themes', ['theme'], unique=False)
    op.create_index(op.f('ix_prediction_themes_verdict'), 'prediction_themes', ['verdict'], unique=False)
    op.create_index(op.f('ix_prediction_themes_verify_outcome'), 'prediction_themes', ['verify_outcome'], unique=False)
    op.create_table('review_action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.String(length=40), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=False),
    sa.Column('proposed_change', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_action_items_category'), 'review_action_items', ['category'], unique=False)
    op.create_index(op.f('ix_review_action_items_created_at'), 'review_action_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_action_items_priority'), 'review_action_items', ['priority'], unique=False)
    op.create_index(op.f('ix_review_action_items_review_id'), 'review_action_items', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_action_items_status'), 'review_action_items', ['status'], unique=False)
    op.create_index(op.f('ix_review_action_items_trade_date'), 'review_action_items', ['trade_date'], unique=False)
    op.create_table('review_meta_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.String(length=40), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('methodology_version', sa.String(length=16), nullable=False),
    sa.Column('dimension', sa.String(length=32), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('effectiveness', sa.String(length=16), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_meta_insights_created_at'), 'review_meta_insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_meta_insights_dimension'), 'review_meta_insights', ['dimension'], unique=False)
    op.create_index(op.f('ix_review_meta_insights_effectiveness'), 'review_meta_insights', ['effectiveness'], unique=False)
    op.create_index(op.f('ix_review_meta_insights_methodology_version'), 'review_meta_insights', ['methodology_version'], unique=False)
    op.create_index(op.f('ix_review_meta_insights_review_id'), 'review_meta_insights', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_meta_insights_trade_date'), 'review_meta_insights', ['trade_date'], unique=False)
    op.create_table('review_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.String(length=40), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('methodology_version', sa.String(length=16), nullable=False),
    sa.Column('model_requested', sa.String(length=64), nullable=False),
    sa.Column('model_actual', sa.String(length=64), nullable=False),
    sa.Column('model_degraded', sa.Integer(), nullable=False),
    sa.Column('model_cost', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('gap_count', sa.Integer(), nullable=False),
    sa.Column('action_item_count', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('report_path', sa.String(length=256), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_reports_generated_at'), 'review_reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_review_reports_methodology_version'), 'review_reports', ['methodology_version'], unique=False)
    op.create_index(op.f('ix_review_reports_review_id'), 'review_reports', ['review_id'], unique=True)
    op.create_index(op.f('ix_review_reports_trade_date'), 'review_reports', ['trade_date'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('group_name', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data_timestamp', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_symbol'), 'watchlist', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_symbol'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_review_reports_trade_date'), table_name='review_reports')
    op.drop_index(op.f('ix_review_reports_review_id'), table_name='review_reports')
    op.drop_index(op.f('ix_review_reports_methodology_version'), table_name='review_reports')
    op.drop_index(op.f('ix_review_reports_generated_at'), table_name='review_reports')
    op.drop_table('review_reports')
    op.drop_index(op.f('ix_review_meta_insights_trade_date'), table_name='review_meta_insights')
    op.drop_index(op.f('ix_review_meta_insights_review_id'), table_name='review_meta_insights')
    op.drop_index(op.f('ix_review_meta_insights_methodology_version'), table_name='review_meta_insights')
    op.drop_index(op.f('ix_review_meta_insights_effectiveness'), table_name='review_meta_insights')
    op.drop_index(op.f('ix_review_meta_insights_dimension'), table_name='review_meta_insights')
    op.drop_index(op.f('ix_review_meta_insights_created_at'), table_name='review_meta_insights')
    op.drop_table('review_meta_insights')
    op.drop_index(op.f('ix_review_action_items_trade_date'), table_name='review_action_items')
    op.drop_index(op.f('ix_review_action_items_status'), table_name='review_action_items')
    op.drop_index(op.f('ix_review_action_items_review_id'), table_name='review_action_items')
    op.drop_index(op.f('ix_review_action_items_priority'), table_name='review_action_items')
    op.drop_index(op.f('ix_review_action_items_created_at'), table_name='review_action_items')
    op.drop_index(op.f('ix_review_action_items_category'), table_name='review_action_items')
    op.drop_table('review_action_items')
    op.drop_index(op.f('ix_prediction_themes_verify_outcome'), table_name='prediction_themes')
    op.drop_index(op.f('ix_prediction_themes_verdict'), table_name='prediction_themes')
    op.drop_index(op.f('ix_prediction_themes_theme'), table_name='prediction_themes')
    op.drop_index(op.f('ix_prediction_themes_target_date'), table_name='prediction_themes')
    op.drop_index(op.f('ix_prediction_themes_prediction_id'), table_name='prediction_themes')
    op.drop_index(op.f('ix_prediction_themes_created_at'), table_name='prediction_themes')
    op.drop_table('prediction_themes')
    op.drop_index(op.f('ix_prediction_reports_verify_status'), table_name='prediction_reports')
    op.drop_index(op.f('ix_prediction_reports_target_date'), table_name='prediction_reports')
    op.drop_index(op.f('ix_prediction_reports_prediction_id'), table_name='prediction_reports')
    op.drop_index(op.f('ix_prediction_reports_created_at'), table_name='prediction_reports')
    op.drop_index(op.f('ix_prediction_reports_context'), table_name='prediction_reports')
    op.drop_table('prediction_reports')
    op.drop_index(op.f('ix_paper_position_symbol'), table_name='paper_position')
    op.drop_table('paper_position')
    op.drop_index(op.f('ix_paper_order_symbol'), table_name='paper_order')
    op.drop_index(op.f('ix_paper_order_status'), table_name='paper_order')
    op.drop_table('paper_order')
    op.drop_table('paper_account')
    op.drop_index(op.f('ix_minute_decisions_trigger_ts'), table_name='minute_decisions')
    op.drop_index(op.f('ix_minute_decisions_trade_date'), table_name='minute_decisions')
    op.drop_index(op.f('ix_minute_decisions_symbol'), table_name='minute_decisions')
    op.drop_index(op.f('ix_minute_decisions_outcome'), table_name='minute_decisions')
    op.drop_index(op.f('ix_minute_decisions_decision_id'), table_name='minute_decisions')
    op.drop_index(op.f('ix_minute_decisions_created_at'), table_name='minute_decisions')
    op.drop_table('minute_decisions')
    # ### end Alembic commands ###
